/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.tools;

import database.DatabaseConnection;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import server.Start;

/**
 *
 * @author 小菜
 */
public class 卡密制作工具 extends javax.swing.JFrame {

    /**
     * Creates new form WinStart
     */
    public 卡密制作工具() {
        ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("image/logo.png"));
        setIconImage(icon.getImage());
        Properties 設定檔 = System.getProperties();
        setTitle("充值/兑换卡控制台");
        initComponents();
        initview();//初始化控件信息

        JOptionPane.showMessageDialog(null, ""
                + "特别友情提示；\r\n"
                + "1.每次尽量不要生成太多充值卡\r\n"
                + "2.生成充值卡后可上架到发卡平台\r\n"
                + "3.请及时删除，避免与之前的卡号弄混\r\n");
        String chars = "1234567890aAbBcCdDeEfFgGhHiIjJkKlLmMNnOoPpQqRrSsTtUuVvWwXxYyZz1234567890";
    }

    public void initview() {
        ((JPanel) getContentPane()).setOpaque(true); // 将JFrame上自带的面板设置为透明，否则背景图片
        UIManager.put("TabbedPane.contentOpaque", true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSN = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldNum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCSPointsValue = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldSN = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAccount = new javax.swing.JTextField();
        jButtonSNSearchByAccount = new javax.swing.JButton();
        jButtonLock = new javax.swing.JButton();
        jButtonSNModify = new javax.swing.JButton();
        jTextFieldType = new javax.swing.JTextField();
        jButtonSNDelete = new javax.swing.JButton();
        jButtonSNSearch = new javax.swing.JButton();
        jButtonUnlock = new javax.swing.JButton();
        jButtonUsed = new javax.swing.JButton();
        jButtonUnused = new javax.swing.JButton();
        jButtonOderByUseTime = new javax.swing.JButton();
        jPanel53 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldProductionNum = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxMoneyb = new javax.swing.JComboBox<>();
        jButtonSNProduction = new javax.swing.JButton();
        jButtonSNRefresh = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldSNValue = new javax.swing.JTextField();

        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableSN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "序号", "类型", "数值", "卡号", "是否使用", "绑定账号", "使用角色", "使用时间", "是否禁用", "生成时间"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSN.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTableSN);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 997, 415));

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel14.setToolTipText("增删改查");

        jLabel12.setText("序  号：");

        jTextFieldNum.setEditable(false);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("类  型：");
        jLabel8.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel9.setText("数  值：");

        jLabel13.setText("卡  号：");

        jLabel10.setText("绑定账号：");

        jTextFieldAccount.setEditable(false);
        jTextFieldAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAccountActionPerformed(evt);
            }
        });

        jButtonSNSearchByAccount.setText("账号查找");
        jButtonSNSearchByAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSNSearchByAccountActionPerformed(evt);
            }
        });

        jButtonLock.setText("禁用");
        jButtonLock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLockActionPerformed(evt);
            }
        });

        jButtonSNModify.setText("修改");
        jButtonSNModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSNModifyActionPerformed(evt);
            }
        });

        jTextFieldType.setEditable(false);

        jButtonSNDelete.setText("删除");
        jButtonSNDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSNDeleteActionPerformed(evt);
            }
        });

        jButtonSNSearch.setText("卡号查找");
        jButtonSNSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSNSearchActionPerformed(evt);
            }
        });

        jButtonUnlock.setText("解禁");
        jButtonUnlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnlockActionPerformed(evt);
            }
        });

        jButtonUsed.setText("已使用");
        jButtonUsed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsedActionPerformed(evt);
            }
        });

        jButtonUnused.setText("未使用");
        jButtonUnused.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnusedActionPerformed(evt);
            }
        });

        jButtonOderByUseTime.setText("数值大小排序");
        jButtonOderByUseTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOderByUseTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonUsed, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldNum, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonSNModify, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSNDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUnused, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldType)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldCSPointsValue)
                            .addComponent(jButtonUnlock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(jButtonLock, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSNSearch)
                                .addGap(4, 4, 4))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jTextFieldSN, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jButtonSNSearchByAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jButtonOderByUseTime)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCSPointsValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLock)
                    .addComponent(jButtonSNModify)
                    .addComponent(jButtonSNSearchByAccount)
                    .addComponent(jButtonSNDelete)
                    .addComponent(jButtonSNSearch)
                    .addComponent(jButtonUnlock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUsed)
                    .addComponent(jButtonUnused)
                    .addComponent(jButtonOderByUseTime))
                .addContainerGap())
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 421, -1, -1));

        jLabel14.setText("数量：");

        jLabel15.setText("类型：");

        jComboBoxMoneyb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "点券", "抵用券", "元宝" }));

        jButtonSNProduction.setText("生成");
        jButtonSNProduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSNProductionActionPerformed(evt);
            }
        });

        jButtonSNRefresh.setText("查看所有");
        jButtonSNRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSNRefreshActionPerformed(evt);
            }
        });

        jButton12.setText("导出");

        jLabel17.setText("面值：");

        javax.swing.GroupLayout jPanel53Layout = new javax.swing.GroupLayout(jPanel53);
        jPanel53.setLayout(jPanel53Layout);
        jPanel53Layout.setHorizontalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel53Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel53Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSNValue))
                    .addGroup(jPanel53Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxMoneyb, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel53Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldProductionNum, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSNRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSNProduction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel53Layout.setVerticalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel53Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldProductionNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSNRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBoxMoneyb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSNProduction))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldSNValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 421, -1, 141));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAccountActionPerformed

    private void jButtonSNSearchByAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSNSearchByAccountActionPerformed
        // TODO add your handling code here:

        String account = jTextFieldAccount.getText();//要查找的账号
        //JOptionPane.showMessageDialog(null, "[信息]：查找卡号成功。");
        String sql = "SELECT * FROM nxcodez WHERE accountid='" + account + "' ORDER BY ID DESC";
        NXDisplay(sql);
    }//GEN-LAST:event_jButtonSNSearchByAccountActionPerformed

    private void jButtonLockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLockActionPerformed
        // TODO add your handling code here:
        try {
            String strNum = jTextFieldNum.getText();//要禁用的序号
            Connection con = DatabaseConnection.getConnection();
            PreparedStatement ps = null;
            ResultSet rs = null;
            ps = con.prepareStatement("UPDATE nxcodez SET isforbid=1 WHERE id=?");
            ps.setInt(1, Integer.parseInt(strNum));
            ps.execute();
            ps.close();
            JOptionPane.showMessageDialog(null, "[信息]:禁用卡号成功。");
            String sql = "SELECT * FROM nxcodez ORDER BY ID DESC";
            NXDisplay(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonLockActionPerformed

    private void jButtonSNModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSNModifyActionPerformed
        // TODO add your handling code here:
        try {
            String strNum = jTextFieldNum.getText();//序号
            String strValue = jTextFieldCSPointsValue.getText();
            String strSN = jTextFieldSN.getText();
            Connection con = DatabaseConnection.getConnection();
            PreparedStatement ps = null;
            //ResultSet rs = null;
            ps = con.prepareStatement("UPDATE nxcodez SET value=?, SN=? WHERE id=?");

            ps.setString(1, strValue);
            ps.setString(2, strSN);
            ps.setInt(3, Integer.parseInt(strNum));
            ps.executeUpdate();
            ps.close();
            JOptionPane.showMessageDialog(null, "[信息]:修改卡号成功。");
            String sql = "SELECT * FROM nxcodez ORDER BY ID DESC";
            NXDisplay(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSNModifyActionPerformed

    private void jButtonSNDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSNDeleteActionPerformed
        // TODO add your handling code here:

        try {
            String strNum = jTextFieldNum.getText();//要删除的序号
            Connection con = DatabaseConnection.getConnection();
            PreparedStatement ps = null;
            ResultSet rs = null;
            ps = con.prepareStatement("DELETE FROM nxcodez WHERE id=?");
            ps.setInt(1, Integer.parseInt(strNum));
            ps.execute();
            JOptionPane.showMessageDialog(null, "[信息]:删除卡号成功。");
            String sql = "SELECT * FROM nxcodez ORDER BY ID DESC";
            NXDisplay(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSNDeleteActionPerformed

    private void jButtonSNSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSNSearchActionPerformed
        // TODO add your handling code here:

        String SN = jTextFieldSN.getText();//要查找的卡号
        //JOptionPane.showMessageDialog(null, "[信息]：查找卡号成功。");
        String sql = "SELECT * FROM nxcodez WHERE sn='" + SN + "' ORDER BY ID DESC";
        NXDisplay(sql);
    }//GEN-LAST:event_jButtonSNSearchActionPerformed

    private void jButtonUnlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnlockActionPerformed
        // TODO add your handling code here:
        try {
            String strNum = jTextFieldNum.getText();//要解禁的卡号
            Connection con = DatabaseConnection.getConnection();
            PreparedStatement ps = null;
            ResultSet rs = null;
            ps = con.prepareStatement("UPDATE nxcodez SET isforbid=0 WHERE id=?");
            ps.setInt(1, Integer.parseInt(strNum));
            ps.execute();
            ps.close();
            JOptionPane.showMessageDialog(null, "[信息]:禁用卡号成功。");
            String sql = "SELECT * FROM nxcodez ORDER BY ID DESC";
            NXDisplay(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonUnlockActionPerformed

    private void jButtonUsedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsedActionPerformed
        // TODO add your handling code here:

        String sql = "SELECT * FROM nxcodez WHERE isused=1 ORDER BY inserttime DESC";
        NXDisplay(sql);
    }//GEN-LAST:event_jButtonUsedActionPerformed

    private void jButtonUnusedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnusedActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * FROM nxcodez WHERE isused=0 ORDER BY ID DESC";
        NXDisplay(sql);
    }//GEN-LAST:event_jButtonUnusedActionPerformed

    private void jButtonOderByUseTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOderByUseTimeActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * FROM nxcodez WHERE isused=1 ORDER BY value DESC";
        NXDisplay(sql);
    }//GEN-LAST:event_jButtonOderByUseTimeActionPerformed

    private void jButtonSNProductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSNProductionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSNProductionActionPerformed

    private void jButtonSNRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSNRefreshActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * FROM nxcodez ORDER BY ID DESC";
        NXDisplay(sql);
    }//GEN-LAST:event_jButtonSNRefreshActionPerformed
    private void NXDisplay(String sql) {
        for (int i = ((DefaultTableModel) (this.jTableSN.getModel())).getRowCount() - 1; i >= 0; i--) {
            ((DefaultTableModel) (this.jTableSN.getModel())).removeRow(i);
        }

        try {
            Connection con = DatabaseConnection.getConnection();
            PreparedStatement ps = null;
            ResultSet rs = null;
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            while (rs.next()) {
                int nType = rs.getInt("type");
                String strType = "点券"; //默认是点券
                if (nType == 1) {
                    strType = "抵用券";
                } else if (nType == 2) {
                    strType = "元宝";
                }

                String strIsused = (rs.getInt("isused") == 0) ? "未使用" : "已使用";

                String strIsForbid = (rs.getInt("isforbid") == 0) ? "正常" : "禁用";

                ((DefaultTableModel) jTableSN.getModel()).insertRow(jTableSN.getRowCount(), new Object[]{
                    rs.getInt("id"),
                    strType,
                    rs.getInt("value"),
                    rs.getString("sn"),
                    strIsused,
                    rs.getInt("accountid"),
                    rs.getString("rolename"),
                    rs.getString("usedtime"),
                    strIsForbid,
                    rs.getString("inserttime")
                });
            }
            ps.close();
            //JOptionPane.showMessageDialog(null, "[信息]:查找全部卡号成功。");

        } catch (SQLException ex) {
            Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
        }

        jTableSN.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int i = jTableSN.getSelectedRow();
                String a = jTableSN.getValueAt(i, 0).toString();
                String a1 = jTableSN.getValueAt(i, 1).toString();
                String a2 = jTableSN.getValueAt(i, 2).toString();
                String a3 = jTableSN.getValueAt(i, 3).toString();
                String a5 = jTableSN.getValueAt(i, 5).toString();
                jTextFieldNum.setText(a);
                jTextFieldType.setText(a1);
                jTextFieldCSPointsValue.setText(a2);
                jTextFieldSN.setText(a3);
                jTextFieldAccount.setText(a5);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButtonLock;
    private javax.swing.JButton jButtonOderByUseTime;
    private javax.swing.JButton jButtonSNDelete;
    private javax.swing.JButton jButtonSNModify;
    private javax.swing.JButton jButtonSNProduction;
    private javax.swing.JButton jButtonSNRefresh;
    private javax.swing.JButton jButtonSNSearch;
    private javax.swing.JButton jButtonSNSearchByAccount;
    private javax.swing.JButton jButtonUnlock;
    private javax.swing.JButton jButtonUnused;
    private javax.swing.JButton jButtonUsed;
    private javax.swing.JComboBox<String> jComboBoxMoneyb;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSN;
    private javax.swing.JTextField jTextFieldAccount;
    private javax.swing.JTextField jTextFieldCSPointsValue;
    private javax.swing.JTextField jTextFieldNum;
    private javax.swing.JTextField jTextFieldProductionNum;
    private javax.swing.JTextField jTextFieldSN;
    private javax.swing.JTextField jTextFieldSNValue;
    private javax.swing.JTextField jTextFieldType;
    // End of variables declaration//GEN-END:variables
}
